apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092 # note the kafka namespace
  topics:
  - quickstart-events
  sink:
#    uri: "http://broker-ingress.knative-eventing.svc.cluster.local/ksandbox/mindwmbroker"
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: graph-events
